# Generated by Django 5.2.9 on 2025-12-14 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField()),
                ('parsed_at', models.DateTimeField(auto_now_add=True)),
                ('checksum', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RunProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle_date', models.DateTimeField(blank=True, null=True)),
                ('tier', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('wave', models.PositiveIntegerField(blank=True, null=True)),
                ('real_time_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('game_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='run_progress', to='core.gamedata')),
            ],
        ),
    ]
