# Generated by Django 5.2.9 on 2025-12-14 22:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_presettag_runprogress_preset_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField()),
                ('canonical_name', models.CharField(max_length=200)),
                ('entity_id', models.CharField(db_index=True, max_length=200)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('raw_row', models.JSONField()),
                ('source_section', models.CharField(max_length=200)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('parse_version', models.CharField(max_length=40)),
                ('deprecated', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['page_url', 'source_section', 'parse_version', 'entity_id'], name='core_wikida_page_ur_3aad7c_idx')],
                'constraints': [models.UniqueConstraint(fields=('page_url', 'source_section', 'parse_version', 'entity_id', 'content_hash'), name='uniq_wikidata_revision')],
            },
        ),
    ]
