# Generated by Django 5.2.9 on 2025-12-14 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_wikidata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.PositiveSmallIntegerField(unique=True)),
                ('unlock_cost_raw', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_name', models.CharField(max_length=120, unique=True)),
                ('unlocked', models.BooleanField(default=False)),
                ('level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGuardianChip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip_name', models.CharField(max_length=120, unique=True)),
                ('owned', models.BooleanField(default=False)),
                ('level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('star', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerUltimateWeapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_name', models.CharField(max_length=120, unique=True)),
                ('unlocked', models.BooleanField(default=False)),
                ('level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('star', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('symbol', models.CharField(blank=True, max_length=12)),
                ('kind', models.CharField(choices=[('unknown', 'Unknown'), ('count', 'Count'), ('percent', 'Percent'), ('seconds', 'Seconds'), ('multiplier', 'Multiplier'), ('currency', 'Currency')], default='unknown', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CardDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('wiki_page_url', models.URLField(blank=True)),
                ('wiki_entity_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('preset_tags', models.ManyToManyField(blank=True, related_name='card_definitions', to='core.presettag')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owned', models.BooleanField(default=False)),
                ('level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('star', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('card_definition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_state', to='core.carddefinition')),
            ],
        ),
        migrations.CreateModel(
            name='CardLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('star', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('raw_row', models.JSONField(blank=True, default=dict)),
                ('card_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='core.carddefinition')),
                ('source_wikidata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_levels', to='core.wikidata')),
            ],
            options={
                'indexes': [models.Index(fields=['card_definition', 'level'], name='core_cardle_card_de_58d521_idx')],
                'constraints': [models.UniqueConstraint(fields=('card_definition', 'level', 'star'), name='uniq_card_level_star')],
            },
        ),
        migrations.CreateModel(
            name='UltimateWeaponParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_name', models.CharField(db_index=True, max_length=120)),
                ('key', models.CharField(max_length=120)),
                ('raw_value', models.CharField(max_length=200)),
                ('source_wikidata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ultimate_weapon_parameters', to='core.wikidata')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unit')),
            ],
            options={
                'indexes': [models.Index(fields=['weapon_name', 'key'], name='core_ultima_weapon__de058f_idx')],
            },
        ),
        migrations.CreateModel(
            name='GuardianChipParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip_name', models.CharField(db_index=True, max_length=120)),
                ('key', models.CharField(max_length=120)),
                ('raw_value', models.CharField(max_length=200)),
                ('source_wikidata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_chip_parameters', to='core.wikidata')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unit')),
            ],
            options={
                'indexes': [models.Index(fields=['chip_name', 'key'], name='core_guardi_chip_na_a036a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='CardParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120)),
                ('raw_value', models.CharField(max_length=200)),
                ('card_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='core.carddefinition')),
                ('source_wikidata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_parameters', to='core.wikidata')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unit')),
            ],
            options={
                'indexes': [models.Index(fields=['card_definition', 'key'], name='core_cardpa_card_de_540a08_idx')],
            },
        ),
        migrations.CreateModel(
            name='BotParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_name', models.CharField(db_index=True, max_length=120)),
                ('key', models.CharField(max_length=120)),
                ('raw_value', models.CharField(max_length=200)),
                ('source_wikidata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_parameters', to='core.wikidata')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unit')),
            ],
            options={
                'indexes': [models.Index(fields=['bot_name', 'key'], name='core_botpar_bot_nam_c0e9aa_idx')],
            },
        ),
    ]
