# Generated by Django 5.2.9 on 2025-12-15 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cardslot_playerbot_playerguardianchip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardslot',
            name='source_wikidata',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='card_slots',
                to='core.wikidata',
            ),
        ),
    ]

