# Generated by Django 5.2.9 on 2025-12-15 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_cardslot_source_wikidata"),
    ]

    operations = [
        migrations.AddField(
            model_name="carddefinition",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="carddefinition",
            name="rarity",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="carddefinition",
            name="unlock_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="cardparameter",
            name="card_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parameters",
                to="core.cardlevel",
            ),
        ),
        migrations.DeleteModel(
            name="BotParameter",
        ),
        migrations.DeleteModel(
            name="GuardianChipParameter",
        ),
        migrations.DeleteModel(
            name="UltimateWeaponParameter",
        ),
        migrations.CreateModel(
            name="BotDefinition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, unique=True)),
                ("wiki_page_url", models.URLField(blank=True)),
                ("wiki_entity_id", models.CharField(blank=True, db_index=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("rarity", models.CharField(blank=True, max_length=80)),
                ("unlock_text", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="GuardianChipDefinition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, unique=True)),
                ("wiki_page_url", models.URLField(blank=True)),
                ("wiki_entity_id", models.CharField(blank=True, db_index=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("rarity", models.CharField(blank=True, max_length=80)),
                ("unlock_text", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="UltimateWeaponDefinition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, unique=True)),
                ("wiki_page_url", models.URLField(blank=True)),
                ("wiki_entity_id", models.CharField(blank=True, db_index=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("rarity", models.CharField(blank=True, max_length=80)),
                ("unlock_text", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="BotLevel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("level", models.PositiveSmallIntegerField()),
                ("star", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("raw_row", models.JSONField(blank=True, default=dict)),
                (
                    "source_wikidata",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bot_levels",
                        to="core.wikidata",
                    ),
                ),
                (
                    "bot_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="core.botdefinition",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("bot_definition", "level", "star"),
                        name="uniq_bot_level_star",
                    )
                ],
                "indexes": [models.Index(fields=["bot_definition", "level"], name="core_botle_bot_def_25b08b_idx")],
            },
        ),
        migrations.CreateModel(
            name="GuardianChipLevel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("level", models.PositiveSmallIntegerField()),
                ("star", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("raw_row", models.JSONField(blank=True, default=dict)),
                (
                    "source_wikidata",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guardian_chip_levels",
                        to="core.wikidata",
                    ),
                ),
                (
                    "guardian_chip_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="core.guardianchipdefinition",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("guardian_chip_definition", "level", "star"),
                        name="uniq_guardian_chip_level_star",
                    )
                ],
                "indexes": [models.Index(fields=["guardian_chip_definition", "level"], name="core_guard_level_00687d_idx")],
            },
        ),
        migrations.CreateModel(
            name="UltimateWeaponLevel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("level", models.PositiveSmallIntegerField()),
                ("star", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("raw_row", models.JSONField(blank=True, default=dict)),
                (
                    "source_wikidata",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ultimate_weapon_levels",
                        to="core.wikidata",
                    ),
                ),
                (
                    "ultimate_weapon_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="core.ultimateweapondefinition",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ultimate_weapon_definition", "level", "star"),
                        name="uniq_ultimate_weapon_level_star",
                    )
                ],
                "indexes": [models.Index(fields=["ultimate_weapon_definition", "level"], name="core_ultim_weapon__6663bd_idx")],
            },
        ),
        migrations.CreateModel(
            name="BotParameter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=120)),
                ("raw_value", models.CharField(max_length=200)),
                (
                    "bot_definition",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="core.botdefinition",
                    ),
                ),
                (
                    "bot_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="core.botlevel",
                    ),
                ),
                (
                    "source_wikidata",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bot_parameters",
                        to="core.wikidata",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.unit",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("bot_level", "key"), name="uniq_bot_level_parameter_key")
                ],
                "indexes": [
                    models.Index(fields=["bot_definition", "key"], name="core_botpa_bot_def_04ffdb_idx"),
                    models.Index(fields=["bot_level", "key"], name="core_botpa_bot_lev_9e485f_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="GuardianChipParameter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=120)),
                ("raw_value", models.CharField(max_length=200)),
                (
                    "guardian_chip_definition",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="core.guardianchipdefinition",
                    ),
                ),
                (
                    "guardian_chip_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="core.guardianchiplevel",
                    ),
                ),
                (
                    "source_wikidata",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guardian_chip_parameters",
                        to="core.wikidata",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.unit",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("guardian_chip_level", "key"),
                        name="uniq_guardian_chip_level_parameter_key",
                    )
                ],
                "indexes": [
                    models.Index(fields=["guardian_chip_definition", "key"], name="core_guardi_chip_de_2aec24_idx"),
                    models.Index(fields=["guardian_chip_level", "key"], name="core_guardi_chip_le_9ed4a0_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UltimateWeaponParameter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=120)),
                ("raw_value", models.CharField(max_length=200)),
                (
                    "source_wikidata",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ultimate_weapon_parameters",
                        to="core.wikidata",
                    ),
                ),
                (
                    "ultimate_weapon_definition",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="core.ultimateweapondefinition",
                    ),
                ),
                (
                    "ultimate_weapon_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="core.ultimateweaponlevel",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.unit",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("ultimate_weapon_level", "key"), name="uniq_uw_level_parameter_key")
                ],
                "indexes": [
                    models.Index(
                        fields=["ultimate_weapon_definition", "key"],
                        name="core_ultim_weapo_d98bfe_idx",
                    ),
                    models.Index(fields=["ultimate_weapon_level", "key"], name="core_ultim_weapo_06009a_idx"),
                ],
            },
        ),
    ]
