# Generated by Django 5.2.9 on 2025-12-15 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_parameter_registry_refactor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gamedata",
            options={"verbose_name": "Game Data", "verbose_name_plural": "Wiki Datum"},
        ),
        migrations.AlterModelOptions(
            name="runprogress",
            options={
                "verbose_name": "Game Progress",
                "verbose_name_plural": "Game Progress",
            },
        ),
        migrations.AlterModelOptions(
            name="wikidata",
            options={"verbose_name": "Wiki Data", "verbose_name_plural": "Wiki Datum"},
        ),
        migrations.RenameIndex(
            model_name="botlevel",
            new_name="core_botlev_bot_def_8cbec0_idx",
            old_name="core_botle_bot_def_25b08b_idx",
        ),
        migrations.RenameIndex(
            model_name="botparameter",
            new_name="core_botpar_bot_def_c08f01_idx",
            old_name="core_botpa_bot_def_04ffdb_idx",
        ),
        migrations.RenameIndex(
            model_name="botparameter",
            new_name="core_botpar_bot_lev_e8145d_idx",
            old_name="core_botpa_bot_lev_9e485f_idx",
        ),
        migrations.RenameIndex(
            model_name="guardianchiplevel",
            new_name="core_guardi_guardia_37b4c0_idx",
            old_name="core_guard_level_00687d_idx",
        ),
        migrations.RenameIndex(
            model_name="guardianchipparameter",
            new_name="core_guardi_guardia_ac5b51_idx",
            old_name="core_guardi_chip_de_2aec24_idx",
        ),
        migrations.RenameIndex(
            model_name="guardianchipparameter",
            new_name="core_guardi_guardia_a53126_idx",
            old_name="core_guardi_chip_le_9ed4a0_idx",
        ),
        migrations.RenameIndex(
            model_name="ultimateweaponlevel",
            new_name="core_ultima_ultimat_98b1e0_idx",
            old_name="core_ultim_weapon__6663bd_idx",
        ),
        migrations.RenameIndex(
            model_name="ultimateweaponparameter",
            new_name="core_ultima_ultimat_d24457_idx",
            old_name="core_ultim_weapo_d98bfe_idx",
        ),
        migrations.RenameIndex(
            model_name="ultimateweaponparameter",
            new_name="core_ultima_ultimat_d1e56d_idx",
            old_name="core_ultim_weapo_06009a_idx",
        ),
        migrations.AlterField(
            model_name="cardparameter",
            name="card_definition",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parameters",
                to="core.carddefinition",
            ),
        ),
        migrations.AddIndex(
            model_name="cardparameter",
            index=models.Index(
                fields=["card_level", "key"], name="core_cardpa_card_le_ad2c19_idx"
            ),
        ),
    ]
