# Generated by Django 5.2.9 on 2025-12-15 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('definitions', '0001_initial'),
        ('player_state', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField()),
                ('parsed_at', models.DateTimeField(auto_now_add=True)),
                ('checksum', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Battle Report',
                'verbose_name_plural': 'Battle Reports',
            },
        ),
        migrations.CreateModel(
            name='BattleReportProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle_date', models.DateTimeField(blank=True, null=True)),
                ('tier', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('wave', models.PositiveIntegerField(blank=True, null=True)),
                ('real_time_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('battle_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='run_progress', to='gamedata.battlereport')),
                ('preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_reports', to='player_state.preset')),
            ],
            options={
                'verbose_name': 'Battle Report Progress',
                'verbose_name_plural': 'Battle Report Progress',
            },
        ),
        migrations.CreateModel(
            name='RunBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('battle_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_bots', to='gamedata.battlereport')),
                ('bot_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_bots', to='definitions.botdefinition')),
            ],
        ),
        migrations.CreateModel(
            name='RunCombatUltimateWeapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('battle_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_combat_uws', to='gamedata.battlereport')),
                ('ultimate_weapon_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_combat_uws', to='definitions.ultimateweapondefinition')),
            ],
        ),
        migrations.CreateModel(
            name='RunGuardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('battle_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_guardians', to='gamedata.battlereport')),
                ('guardian_chip_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_guardians', to='definitions.guardianchipdefinition')),
            ],
        ),
        migrations.CreateModel(
            name='RunUtilityUltimateWeapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('battle_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_utility_uws', to='gamedata.battlereport')),
                ('ultimate_weapon_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_utility_uws', to='definitions.ultimateweapondefinition')),
            ],
        ),
    ]
