# Generated by Django 5.2.9 on 2025-12-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlereportprogress',
            name='cash_earned',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battlereportprogress',
            name='cash_earned_raw',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='battlereportprogress',
            name='cells_earned',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battlereportprogress',
            name='coins_earned',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battlereportprogress',
            name='coins_earned_raw',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='battlereportprogress',
            name='gem_blocks_tapped',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battlereportprogress',
            name='interest_earned',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battlereportprogress',
            name='interest_earned_raw',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='battlereportprogress',
            name='killed_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='battlereportprogress',
            name='reroll_shards_earned',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
