# Generated by Django 5.2.9 on 2025-12-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0002_battlereportprogress_cash_earned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlereportprogress',
            name='preset_color_snapshot',
            field=models.CharField(blank=True, default='', help_text='Preset color key captured at assignment time for historical badge rendering.', max_length=20),
        ),
        migrations.AddField(
            model_name='battlereportprogress',
            name='preset_name_snapshot',
            field=models.CharField(blank=True, default='', help_text='Preset label captured at assignment time for historical display.', max_length=80),
        ),
    ]
