# Generated by Django 5.2.9 on 2025-12-27 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamedata", "0005_battlereportprogress_is_tournament"),
        ("player_state", "0009_goaltarget"),
    ]

    operations = [
        migrations.CreateModel(
            name="BattleReportDerivedMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("values", models.JSONField(blank=True, default=dict)),
                ("raw_values", models.JSONField(blank=True, default=dict)),
                (
                    "battle_report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="derived_metrics",
                        to="gamedata.battlereport",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battle_report_derived_metrics",
                        to="player_state.player",
                    ),
                ),
            ],
            options={
                "verbose_name": "Battle Report Derived Metrics",
                "verbose_name_plural": "Battle Report Derived Metrics",
            },
        ),
    ]
