# Generated by Django 5.2.13 on 2026-04-17 20:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0009_battlereport_is_hidden'),
        ('player_state', '0015_seed_additional_explore_query_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlereportprogress',
            name='dissonance_levels_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text="Stored Dissonance level snapshot per type for this run's tier at import time."),
        ),
        migrations.AddField(
            model_name='battlereportprogress',
            name='dissonance_type',
            field=models.CharField(blank=True, choices=[('attack', 'Attack'), ('defense', 'Defense'), ('utility', 'Utility'), ('ultimate_weapon', 'Ultimate Weapon')], help_text='Optional Dissonance type recorded during import.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='battlereportprogress',
            name='is_dissonance',
            field=models.BooleanField(default=False, help_text='Manual override: mark this run as a Dissonance run when the pasted text does not indicate it.'),
        ),
        migrations.CreateModel(
            name='PlayerDissonanceTierBoost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.PositiveSmallIntegerField()),
                ('dissonance_type', models.CharField(choices=[('attack', 'Attack'), ('defense', 'Defense'), ('utility', 'Utility'), ('ultimate_weapon', 'Ultimate Weapon')], max_length=20)),
                ('current_level', models.PositiveIntegerField(default=1)),
                ('highest_effective_multiplier', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=10)),
                ('top_effective_multipliers', models.JSONField(blank=True, default=list)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dissonance_tier_boosts', to='player_state.player')),
            ],
            options={
                'verbose_name': 'Player Dissonance Tier Boost',
                'verbose_name_plural': 'Player Dissonance Tier Boosts',
                'constraints': [models.UniqueConstraint(fields=('player', 'tier', 'dissonance_type'), name='uniq_player_dissonance_tier_type')],
            },
        ),
    ]
