# Generated by Django 5.2.9 on 2025-12-15 21:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('wiki_page_url', models.URLField(blank=True)),
                ('wiki_entity_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuardianChipDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('wiki_page_url', models.URLField(blank=True)),
                ('wiki_entity_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UltimateWeaponDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('wiki_page_url', models.URLField(blank=True)),
                ('wiki_entity_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('symbol', models.CharField(blank=True, max_length=12)),
                ('kind', models.CharField(choices=[('unknown', 'Unknown'), ('count', 'Count'), ('percent', 'Percent'), ('seconds', 'Seconds'), ('multiplier', 'Multiplier'), ('currency', 'Currency')], default='unknown', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BotParameterDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('angle', 'Angle'), ('cash_bonus', 'Cash Bonus'), ('chance', 'Chance'), ('coins_bonus', 'Coins Bonus'), ('coins_multiplier', 'Coins Multiplier'), ('cooldown', 'Cooldown'), ('damage', 'Damage'), ('damage_multiplier', 'Damage Multiplier'), ('damage_percent', 'Damage %'), ('double_find_chance', 'Double Find Chance'), ('duration', 'Duration'), ('effect_wave', 'Effect Wave'), ('find_chance', 'Find Chance'), ('max_recovery', 'Max Recovery'), ('multiplier', 'Multiplier'), ('percentage', 'Percentage'), ('quantity', 'Quantity'), ('range', 'Range'), ('recovery_amount', 'Recovery Amount'), ('size', 'Size'), ('slow', 'Slow'), ('targets', 'Targets')], max_length=40)),
                ('display_name', models.CharField(max_length=120)),
                ('unit_kind', models.CharField(choices=[('unknown', 'Unknown'), ('count', 'Count'), ('percent', 'Percent'), ('seconds', 'Seconds'), ('multiplier', 'Multiplier'), ('currency', 'Currency')], default='unknown', max_length=20)),
                ('bot_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_definitions', to='definitions.botdefinition')),
            ],
        ),
        migrations.CreateModel(
            name='GuardianChipParameterDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('angle', 'Angle'), ('cash_bonus', 'Cash Bonus'), ('chance', 'Chance'), ('coins_bonus', 'Coins Bonus'), ('coins_multiplier', 'Coins Multiplier'), ('cooldown', 'Cooldown'), ('damage', 'Damage'), ('damage_multiplier', 'Damage Multiplier'), ('damage_percent', 'Damage %'), ('double_find_chance', 'Double Find Chance'), ('duration', 'Duration'), ('effect_wave', 'Effect Wave'), ('find_chance', 'Find Chance'), ('max_recovery', 'Max Recovery'), ('multiplier', 'Multiplier'), ('percentage', 'Percentage'), ('quantity', 'Quantity'), ('range', 'Range'), ('recovery_amount', 'Recovery Amount'), ('size', 'Size'), ('slow', 'Slow'), ('targets', 'Targets')], max_length=40)),
                ('display_name', models.CharField(max_length=120)),
                ('unit_kind', models.CharField(choices=[('unknown', 'Unknown'), ('count', 'Count'), ('percent', 'Percent'), ('seconds', 'Seconds'), ('multiplier', 'Multiplier'), ('currency', 'Currency')], default='unknown', max_length=20)),
                ('guardian_chip_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_definitions', to='definitions.guardianchipdefinition')),
            ],
        ),
        migrations.CreateModel(
            name='UltimateWeaponParameterDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('angle', 'Angle'), ('cash_bonus', 'Cash Bonus'), ('chance', 'Chance'), ('coins_bonus', 'Coins Bonus'), ('coins_multiplier', 'Coins Multiplier'), ('cooldown', 'Cooldown'), ('damage', 'Damage'), ('damage_multiplier', 'Damage Multiplier'), ('damage_percent', 'Damage %'), ('double_find_chance', 'Double Find Chance'), ('duration', 'Duration'), ('effect_wave', 'Effect Wave'), ('find_chance', 'Find Chance'), ('max_recovery', 'Max Recovery'), ('multiplier', 'Multiplier'), ('percentage', 'Percentage'), ('quantity', 'Quantity'), ('range', 'Range'), ('recovery_amount', 'Recovery Amount'), ('size', 'Size'), ('slow', 'Slow'), ('targets', 'Targets')], max_length=40)),
                ('display_name', models.CharField(max_length=120)),
                ('unit_kind', models.CharField(choices=[('unknown', 'Unknown'), ('count', 'Count'), ('percent', 'Percent'), ('seconds', 'Seconds'), ('multiplier', 'Multiplier'), ('currency', 'Currency')], default='unknown', max_length=20)),
                ('ultimate_weapon_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_definitions', to='definitions.ultimateweapondefinition')),
            ],
        ),
        migrations.CreateModel(
            name='WikiData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField()),
                ('canonical_name', models.CharField(max_length=200)),
                ('entity_id', models.CharField(db_index=True, max_length=200)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('raw_row', models.JSONField()),
                ('source_section', models.CharField(max_length=200)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('parse_version', models.CharField(max_length=40)),
                ('deprecated', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Wiki Data',
                'verbose_name_plural': 'Wiki Data',
                'indexes': [models.Index(fields=['page_url', 'source_section', 'parse_version', 'entity_id'], name='definitions_page_ur_41e229_idx')],
                'constraints': [models.UniqueConstraint(fields=('page_url', 'source_section', 'parse_version', 'entity_id', 'content_hash'), name='uniq_wikidata_revision')],
            },
        ),
        migrations.CreateModel(
            name='UltimateWeaponParameterLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('value_raw', models.CharField(max_length=200)),
                ('cost_raw', models.CharField(max_length=200)),
                ('currency', models.CharField(choices=[('medals', 'Medals'), ('stones', 'Stones'), ('bits', 'Bits')], default='stones', max_length=20)),
                ('parameter_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='definitions.ultimateweaponparameterdefinition')),
                ('source_wikidata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uw_parameter_levels', to='definitions.wikidata')),
            ],
        ),
        migrations.AddField(
            model_name='ultimateweapondefinition',
            name='source_wikidata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ultimate_weapon_definitions', to='definitions.wikidata'),
        ),
        migrations.CreateModel(
            name='GuardianChipParameterLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('value_raw', models.CharField(max_length=200)),
                ('cost_raw', models.CharField(max_length=200)),
                ('currency', models.CharField(choices=[('medals', 'Medals'), ('stones', 'Stones'), ('bits', 'Bits')], default='bits', max_length=20)),
                ('parameter_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='definitions.guardianchipparameterdefinition')),
                ('source_wikidata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_parameter_levels', to='definitions.wikidata')),
            ],
        ),
        migrations.AddField(
            model_name='guardianchipdefinition',
            name='source_wikidata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_chip_definitions', to='definitions.wikidata'),
        ),
        migrations.CreateModel(
            name='CardDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('wiki_page_url', models.URLField(blank=True)),
                ('wiki_entity_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('rarity', models.CharField(blank=True, max_length=80)),
                ('unlock_text', models.TextField(blank=True)),
                ('source_wikidata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_definitions', to='definitions.wikidata')),
            ],
        ),
        migrations.CreateModel(
            name='BotParameterLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('value_raw', models.CharField(max_length=200)),
                ('cost_raw', models.CharField(max_length=200)),
                ('currency', models.CharField(choices=[('medals', 'Medals'), ('stones', 'Stones'), ('bits', 'Bits')], default='medals', max_length=20)),
                ('parameter_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='definitions.botparameterdefinition')),
                ('source_wikidata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_parameter_levels', to='definitions.wikidata')),
            ],
        ),
        migrations.AddField(
            model_name='botdefinition',
            name='source_wikidata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_definitions', to='definitions.wikidata'),
        ),
        migrations.AddConstraint(
            model_name='botparameterdefinition',
            constraint=models.UniqueConstraint(fields=('bot_definition', 'key'), name='uniq_bot_param_definition_key'),
        ),
        migrations.AddConstraint(
            model_name='guardianchipparameterdefinition',
            constraint=models.UniqueConstraint(fields=('guardian_chip_definition', 'key'), name='uniq_guardian_param_definition_key'),
        ),
        migrations.AddConstraint(
            model_name='ultimateweaponparameterdefinition',
            constraint=models.UniqueConstraint(fields=('ultimate_weapon_definition', 'key'), name='uniq_uw_param_definition_key'),
        ),
        migrations.AddConstraint(
            model_name='ultimateweaponparameterlevel',
            constraint=models.UniqueConstraint(fields=('parameter_definition', 'level'), name='uniq_uw_param_level'),
        ),
        migrations.AddConstraint(
            model_name='ultimateweaponparameterlevel',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'stones')), name='uw_param_currency_stones'),
        ),
        migrations.AddConstraint(
            model_name='guardianchipparameterlevel',
            constraint=models.UniqueConstraint(fields=('parameter_definition', 'level'), name='uniq_guardian_param_level'),
        ),
        migrations.AddConstraint(
            model_name='guardianchipparameterlevel',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'bits')), name='guardian_param_currency_bits'),
        ),
        migrations.AddConstraint(
            model_name='botparameterlevel',
            constraint=models.UniqueConstraint(fields=('parameter_definition', 'level'), name='uniq_bot_param_level'),
        ),
        migrations.AddConstraint(
            model_name='botparameterlevel',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'medals')), name='bot_param_currency_medals'),
        ),
    ]
