# Generated by Django 5.2.9 on 2025-12-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddefinition',
            name='effect_raw',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='botparameterdefinition',
            name='key',
            field=models.CharField(choices=[('angle', 'Angle'), ('cash_bonus', 'Cash Bonus'), ('chance', 'Chance'), ('coins_bonus', 'Coins Bonus'), ('coins_multiplier', 'Coins Multiplier'), ('cooldown', 'Cooldown'), ('damage', 'Damage'), ('damage_multiplier', 'Damage Multiplier'), ('damage_percent', 'Damage Percent'), ('damage_reduction', 'Damage Reduction'), ('double_find_chance', 'Double Find Chance'), ('duration', 'Duration'), ('effect_wave', 'Effect Wave'), ('find_chance', 'Find Chance'), ('linger', 'Linger'), ('max_recovery', 'Max Recovery'), ('multiplier', 'Multiplier'), ('percentage', 'Percentage'), ('quantity', 'Quantity'), ('range', 'Range'), ('recovery_amount', 'Recovery Amount'), ('size', 'Size'), ('slow', 'Slow'), ('targets', 'Targets')], max_length=40),
        ),
        migrations.AlterField(
            model_name='guardianchipparameterdefinition',
            name='key',
            field=models.CharField(choices=[('angle', 'Angle'), ('cash_bonus', 'Cash Bonus'), ('chance', 'Chance'), ('coins_bonus', 'Coins Bonus'), ('coins_multiplier', 'Coins Multiplier'), ('cooldown', 'Cooldown'), ('damage', 'Damage'), ('damage_multiplier', 'Damage Multiplier'), ('damage_percent', 'Damage Percent'), ('damage_reduction', 'Damage Reduction'), ('double_find_chance', 'Double Find Chance'), ('duration', 'Duration'), ('effect_wave', 'Effect Wave'), ('find_chance', 'Find Chance'), ('linger', 'Linger'), ('max_recovery', 'Max Recovery'), ('multiplier', 'Multiplier'), ('percentage', 'Percentage'), ('quantity', 'Quantity'), ('range', 'Range'), ('recovery_amount', 'Recovery Amount'), ('size', 'Size'), ('slow', 'Slow'), ('targets', 'Targets')], max_length=40),
        ),
        migrations.AlterField(
            model_name='ultimateweaponparameterdefinition',
            name='key',
            field=models.CharField(choices=[('angle', 'Angle'), ('cash_bonus', 'Cash Bonus'), ('chance', 'Chance'), ('coins_bonus', 'Coins Bonus'), ('coins_multiplier', 'Coins Multiplier'), ('cooldown', 'Cooldown'), ('damage', 'Damage'), ('damage_multiplier', 'Damage Multiplier'), ('damage_percent', 'Damage Percent'), ('damage_reduction', 'Damage Reduction'), ('double_find_chance', 'Double Find Chance'), ('duration', 'Duration'), ('effect_wave', 'Effect Wave'), ('find_chance', 'Find Chance'), ('linger', 'Linger'), ('max_recovery', 'Max Recovery'), ('multiplier', 'Multiplier'), ('percentage', 'Percentage'), ('quantity', 'Quantity'), ('range', 'Range'), ('recovery_amount', 'Recovery Amount'), ('size', 'Size'), ('slow', 'Slow'), ('targets', 'Targets')], max_length=40),
        ),
    ]
