# Generated by Django 5.2.9 on 2025-12-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0002_carddefinition_effect_raw_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatchBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boundary_date', models.DateField(unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Patch boundary',
                'verbose_name_plural': 'Patch boundaries',
            },
        ),
    ]
