# Generated by Django 5.2.9 on 2025-12-15 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('definitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_slug', models.CharField(db_index=True, max_length=200)),
                ('unlocked', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('bot_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_bots', to='definitions.botdefinition')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='player_state.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerBotParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parameter_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_levels', to='definitions.botparameterdefinition')),
                ('player_bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='player_state.playerbot')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_slug', models.CharField(db_index=True, max_length=200)),
                ('stars_unlocked', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_cards', to='definitions.carddefinition')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='player_state.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGuardianChip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian_chip_slug', models.CharField(db_index=True, max_length=200)),
                ('unlocked', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('guardian_chip_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_guardian_chips', to='definitions.guardianchipdefinition')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_chips', to='player_state.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGuardianChipParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parameter_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_levels', to='definitions.guardianchipparameterdefinition')),
                ('player_guardian_chip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='player_state.playerguardianchip')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerUltimateWeapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimate_weapon_slug', models.CharField(db_index=True, max_length=200)),
                ('unlocked', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ultimate_weapons', to='player_state.player')),
                ('ultimate_weapon_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_ultimate_weapons', to='definitions.ultimateweapondefinition')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerUltimateWeaponParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parameter_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_levels', to='definitions.ultimateweaponparameterdefinition')),
                ('player_ultimate_weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='player_state.playerultimateweapon')),
            ],
        ),
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presets', to='player_state.player')),
            ],
        ),
        migrations.AddConstraint(
            model_name='playerbot',
            constraint=models.UniqueConstraint(fields=('player', 'bot_slug'), name='uniq_player_bot_slug'),
        ),
        migrations.AddConstraint(
            model_name='playerbotparameter',
            constraint=models.UniqueConstraint(fields=('player_bot', 'parameter_definition'), name='uniq_player_bot_param'),
        ),
        migrations.AddConstraint(
            model_name='playercard',
            constraint=models.UniqueConstraint(fields=('player', 'card_slug'), name='uniq_player_card_slug'),
        ),
        migrations.AddConstraint(
            model_name='playerguardianchip',
            constraint=models.UniqueConstraint(fields=('player', 'guardian_chip_slug'), name='uniq_player_guardian_slug'),
        ),
        migrations.AddConstraint(
            model_name='playerguardianchipparameter',
            constraint=models.UniqueConstraint(fields=('player_guardian_chip', 'parameter_definition'), name='uniq_player_guardian_param'),
        ),
        migrations.AddConstraint(
            model_name='playerultimateweapon',
            constraint=models.UniqueConstraint(fields=('player', 'ultimate_weapon_slug'), name='uniq_player_uw_slug'),
        ),
        migrations.AddConstraint(
            model_name='playerultimateweaponparameter',
            constraint=models.UniqueConstraint(fields=('player_ultimate_weapon', 'parameter_definition'), name='uniq_player_uw_param'),
        ),
        migrations.AddConstraint(
            model_name='preset',
            constraint=models.UniqueConstraint(fields=('player', 'name'), name='uniq_player_preset_name'),
        ),
    ]
