# Generated by Django 5.2.9 on 2025-12-16 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_state', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='card_slots_unlocked',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playercard',
            name='inventory_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PlayerCardPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preset_links', to='player_state.playercard')),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_links', to='player_state.preset')),
            ],
        ),
        migrations.AddField(
            model_name='playercard',
            name='presets',
            field=models.ManyToManyField(blank=True, related_name='player_cards', through='player_state.PlayerCardPreset', to='player_state.preset'),
        ),
        migrations.AddConstraint(
            model_name='playercardpreset',
            constraint=models.UniqueConstraint(fields=('player_card', 'preset'), name='uniq_player_card_preset'),
        ),
    ]
