# Generated by Django 5.2.9 on 2025-12-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player_state", "0002_player_card_slots_unlocked_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="preset",
            name="color",
            field=models.CharField(blank=True, choices=[("blue", "Blue"), ("teal", "Teal"), ("green", "Green"), ("orange", "Orange"), ("red", "Red"), ("purple", "Purple")], default="", max_length=20),
        ),
    ]

