# Generated by Django 5.2.9 on 2025-12-18 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_state', '0005_parameter_effective_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('chart_builder', models.JSONField(default=dict)),
                ('chart_context', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_snapshots', to='player_state.player')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('player', 'name'), name='uniq_player_chart_snapshot_name')],
            },
        ),
    ]
