# Generated by Django 5.2.9 on 2025-12-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_state', '0006_chartsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartsnapshot',
            name='config',
            field=models.JSONField(default=dict, help_text='Versioned ChartConfigDTO payload used for deterministic chart execution.'),
        ),
        migrations.AddField(
            model_name='chartsnapshot',
            name='target',
            field=models.CharField(default='charts', help_text='Dashboard target for applying this snapshot (e.g. charts, ultimate_weapons).', max_length=40),
        ),
    ]
