# Generated by Django 5.2.9 on 2025-12-25 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_state', '0008_merge_0006_player_user_and_player_fks_0007_chartsnapshot_config_chartsnapshot_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('bot', 'Bot'), ('guardian_chip', 'Guardian chip'), ('ultimate_weapon', 'Ultimate weapon')], db_index=True, max_length=40)),
                ('goal_key', models.CharField(db_index=True, max_length=240)),
                ('target_level', models.PositiveSmallIntegerField()),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('assumed_current_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_current_level_assumed', models.BooleanField(default=False)),
                ('last_recalculated_at', models.DateTimeField(blank=True, null=True)),
                ('cost_source_revision', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_targets', to='player_state.player')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('player', 'goal_type', 'goal_key'), name='uniq_goal_target_key')],
            },
        ),
    ]
